apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: api-migration
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/base/api
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: batch/v1
      kind: Job
      name: db-migration
      namespace: url-minifier
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: api-app
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: api-migration
  path: ./k8s/base/api-deploy
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
