apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: url-minifier
data:
  HOST: "0.0.0.0"
  PORT: "8080"
  DEBUG: "false"
  POSTGRES_HOST: "postgres-postgresql.url-minifier.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "database"
  REDIS_HOST: "redis-master.url-minifier.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  GOOGLE_CALLBACK_URL: "https://url-minifier.olyxz16.fr/auth/google/callback"
  GOMEMLIMIT: 230MiB
