apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: url-minifier
type: Opaque
stringData:
    token-secret: ENC[AES256_GCM,data:5Tk30sqJzwF48fGJuDcaeDjixSUT4mgqiKLLRD8EWphyytTJJdzmf8wpLA0=,iv:BM+VgbTohyDGlXhs5bo8c6VxFwJK0VSH6hMhLnTf6AQ=,tag:x/AxnOIr8Nj57yRPLZOwcg==,type:str]
    google-access-key-id: ENC[AES256_GCM,data:YndxXggoskEQXH+YXcYH0K7wU1dHDD8t/qA/MgrggvZkE4sRyTvXm6OPXIBkOoDaZzJt52fB2Zho4JEnsJDPNsrX8aAA+kvE,iv:w5qPHgQzq3pSh7k2fCKzi3Cc6YPwvtGDEaQSGxZOPh8=,tag:S41ayCYMFfe2w48LtQYogw==,type:str]
    google-secret-access-key: ENC[AES256_GCM,data:cc2XkcXO2qUkOwVVj0hegijzyfuoH2btF9nndGZnmGHpoIE=,iv:Hm+f2wG4gaavOLuI6FtUW4rUeTlRF4bhWH7pOUmgra4=,tag:JYGBQOG4QJiKwrRbI3hAog==,type:str]
    database-url: ENC[AES256_GCM,data:PeVrWDpCpjRYSlB7rdxp0lhQ0ZAtWLHO6bxy58OJVeThTu7FGq+QBXbLSZiSStOVrHpZPwLWs1QTG+wSvUfTHgu/LUsiCI8TQAT5OUC3WrwdUfrX8yx81gTgFyykRcgNFHdxwzH24Bk1Q4hqSH0YLQ==,iv:D2Mc2wMwyoLHccZ0Zofmb3Es0HV6FkQbQyn99jv6p/c=,tag:5hPCF3C+R8PyVqX6d50ukQ==,type:str]
    redis-password: ENC[AES256_GCM,data:ODUP02iKtcboZfZYizvELdeKSKMmy/fzZV/8zRw7CCh0vcqnhJuVRg4/1/s=,iv:vT3nEbPwdS2ATA5mbqhvVyE/hSKLjD4wRNguM0QS//4=,tag:j7KZfY7mk6T2VvI1Bnllog==,type:str]
sops:
    age:
        - recipient: age1g752ky89kud2ldcgfvyzvdgsx98ydr3cwjzpk460m7mztr3ne48ssme2l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY1BhcHh4RmtRTGxwUENI
            TS9TSkMvZUx1QXdXMENpSExOVlF1VUxqVFVnCklFWllFbEtjeXVZNStvUmpYK29n
            UTBGSkp2bi9VQk1KVzhCZnNSem1SV0kKLS0tIDZZMW9vcHlodHd6cld4S1ZBS1o2
            alVHOHJBem41TDlZdzZtMlh3SitwZGcKGf5HnbWVCkKLN5wM0utulR/Iq696ItMP
            iv9oEYwpo8NdrH2Y4tzd+YPAbOVZY0GFKxj8fz5uxW1Q7fZd740gHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T13:44:53Z"
    mac: ENC[AES256_GCM,data:Jq7uWOyu4RMPoUo9w8pq+/M3AEnbJEKY0wDyIrMXT4KjK6aAQyO3ZCqW6wXfDUYqi2o1213FIWXUILD6SjMyP5cZO+0rpidYCtjB4js1DIdpF/48mkTshgcFTFY9Ry13f/WIhnVKAefD5alz1imj4YZYNq4kGMAY+mm0pIAQJvo=,iv:3s85ajeB0atGW/VGDIH92NYO42Ceh0Q6UjEQ/kRIsgU=,tag:2ysCphvamfyBEiHQLf9xDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
