apiVersion: v1
kind: Secret
metadata:
    name: redis-secrets
    namespace: url-minifier
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:XOMj8+dXVlEjcyhtweB6GR2Wq/0f/Gm991TT6Xv6lvhDwPWTFq9ABop7MHs=,iv:ZShs5MbJkmx7VlaOkTgqthDARDYSXsBMNjJeODM3VVY=,tag:3OhoOgXL86bR+KZ9SKd4LA==,type:str]
sops:
    age:
        - recipient: age1g752ky89kud2ldcgfvyzvdgsx98ydr3cwjzpk460m7mztr3ne48ssme2l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybjYrcDl3cEpqNXhlTHNW
            ekkyOFNkUW1OK1o5UlgxYkdqc3dCSXFoYm1nCkpDM1VSYllIc1htVjBCOVNPVFZW
            ZU9iR0FnSVpyRlZxRVcrR2JwTm5pa0kKLS0tIEZrQlozZko5TG94bUpJVEkzOEhY
            Yy94Ky9wNkF6ZHdqRGllelYzQVgrdlEKI7k9SmSw5vHuydB0mrYhoDzsyq2YZnj7
            IvEkN7J9TPP64h8NZ/s/Uy85IUaSvDC+TvBXvp2S3LJsiZ/M/vU7ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:52:46Z"
    mac: ENC[AES256_GCM,data:/22UAZxa/Q8Y1S5yvcgYaLB4ghCYCaTAskYuMOaBu8pvZwaXA2T72/2V3+vG5hbI370xikf6TZJde3S9n+HMAXzf8/h3ynb9ItP8JwszBsyOndXZWIpCl1yOV5v3dkBuNc/MpGdLOta6FLnPPZE0AWyYddlbGboZhHhlMyycJiI=,iv:sfcsu/Og0DOo9ZmAObffTE4kQSJvly8xODmK7vLe5Bw=,tag:rYhFn+4sfzlFmr1YofaC0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
