apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: url-minifier-api-sync
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: url-minifier-repo
  path: ./k8s/overlays/production
  prune: true
  dependsOn:
    - name: url-minifier-core-sync
  decryption:
    provider: sops
    secretRef:
      name: url-minifier-sops-age
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: url-minifier-repo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/Olyxz16/url-minifier.git
  ref:
    branch: main
  secretRef:
    name: url-minifier-ssh-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: url-minifier-image-repo
  namespace: flux-system
spec:
  image: ghcr.io/olyxz16/url-minifier/api
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: url-minifier-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: url-minifier-image-repo
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: url-minifier-flux-image-updates
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'chore: update image to {{ range .Updated.Images }}{{ println . }}{{ end }}'
    push:
      branch: main
