apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: url-minifier
stringData:
    admin-pass: ENC[AES256_GCM,data:cyyuHpiG0mdI4dxqlLpQSA==,iv:Vqe8l3tdTlV4b3rQp8dZMBopBAeoAezkv+62Zq5EBfg=,tag:kI5y9aHO2F6QmJsCyJcgrw==,type:str]
    user-pass: ENC[AES256_GCM,data:3V4QpfiKW4A6gaJEOz5+,iv:DZ993+DSt10y9X/h6NKlhynB/HBsZkVRVXBzVaqvv9Q=,tag:wBPb8ZISGSB5W0zdBM6Ckw==,type:str]
sops:
    age:
        - recipient: age1g752ky89kud2ldcgfvyzvdgsx98ydr3cwjzpk460m7mztr3ne48ssme2l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzhLOGFwdCtZRS8xMkRT
            NjMyT3NtUlh4UmZMOWlHcFAxOVlLbVRNcHljCmdIcjNOSlltcm5YeTFpL09Sckx1
            Wm14M3czUmdMRVZ4QStDcTdIRnBQd28KLS0tIGw4bXJJbS8rZEROaG56QU5FVThU
            aFYxbWltWW9NRlN2OXRXdFdMbGxtdnMKJdFkGRtLJNvWt6XVmDlbn/7IQ4lX3/FD
            zk1dHmGPapoDRGIBL3hEW89TDYay15vDmNSJnlowCroQs2TjtKJCjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T10:32:46Z"
    mac: ENC[AES256_GCM,data:2LE67+hEug+IyOlEd9if3iXYJvIsdRfSuiwBl3mRW0D4k/lsloGQkxHj2Uj2NNMNhGJQtJmGdjNrc2sMgjNJqBGcV5x+XBV6R+KEY5fJxtGSVa4KA9m3tHlfsSl5+eOyKB8Lk7Ov1NxFx9vyDSGvjmok/lyhgGSRGvI66jTbhGM=,iv:f7kClg/pbkPq5lmSLzVNvw5cet1DG8vqbfEwadD2OZU=,tag:Gph10hJ1cjCoMwryuDz31w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
