apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-servicemonitor
  namespace: url-minifier
  labels:
    release: prometheus
    app: url-minifier-api
spec:
  selector:
    matchLabels:
      app: url-minifier-api
  namespaceSelector:
    matchNames:
      - url-minifier
  endpoints:
    - port: http # This needs to match the named port in the service
      path: /metrics
      interval: 30s
