apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: url-minifier-api-sync
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: url-minifier-repo
  path: ./k8s/overlays/staging
  prune: true
  dependsOn:
    - name: url-minifier-core-sync
  decryption:
    provider: sops
    secretRef:
      name: url-minifier-sops-age
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: url-minifier-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Olyxz16/url-minifier.git
  ref:
    branch: staging
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: url-minifier-image-repo
  namespace: flux-system
spec:
  image: ghcr.io/olyxz16/url-minifier/api
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: url-minifier-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: url-minifier-image-repo
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^staging-(?P<ts>[0-9]+)-[a-f0-9]+$'
    extract: '$ts'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: url-minifier-flux-image-updates
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: staging
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    messageTemplate: 'chore: update image: {{range .Changed.Changes}}{{print .OldValue}} -> {{print .NewValue}}{{end}}'
    push:
      branch: staging
