apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: url-minifier-postgres-sync
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/overlays/staging/postgres
  prune: true
  dependsOn:
    - name: url-minifier-core-sync
  decryption:
    provider: sops
    secretRef:
      name: url-minifier-sops-age
