// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          pgtype.UUID
	CreatorID   pgtype.UUID
	ShortUrl    string
	RedirectUrl string
	HitCount    int32
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Provider  string
	CreatedAt pgtype.Timestamptz
}
