// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (id, creator_id, short_url, redirect_url)
VALUES ($1, $2, $3, $4)
RETURNING id, creator_id, short_url, redirect_url, hit_count, created_at, expires_at
`

type CreateUrlParams struct {
	ID          pgtype.UUID
	CreatorID   pgtype.UUID
	ShortUrl    string
	RedirectUrl string
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl,
		arg.ID,
		arg.CreatorID,
		arg.ShortUrl,
		arg.RedirectUrl,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.ShortUrl,
		&i.RedirectUrl,
		&i.HitCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteUrl = `-- name: DeleteUrl :exec
DELETE FROM urls
WHERE id=$1
`

func (q *Queries) DeleteUrl(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUrl, id)
	return err
}

const getUrlById = `-- name: GetUrlById :one
SELECT id, creator_id, short_url, redirect_url, hit_count, created_at, expires_at FROM urls
WHERE id=$1
LIMIT(1)
`

func (q *Queries) GetUrlById(ctx context.Context, id pgtype.UUID) (Url, error) {
	row := q.db.QueryRow(ctx, getUrlById, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.ShortUrl,
		&i.RedirectUrl,
		&i.HitCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUrlByShort = `-- name: GetUrlByShort :one
SELECT id, creator_id, short_url, redirect_url, hit_count, created_at, expires_at FROM urls
WHERE short_url=$1
LIMIT(1)
`

func (q *Queries) GetUrlByShort(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getUrlByShort, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.ShortUrl,
		&i.RedirectUrl,
		&i.HitCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateHitCount = `-- name: UpdateHitCount :exec
UPDATE urls
SET hit_count=hit_count+1
WHERE id=$1
`

func (q *Queries) UpdateHitCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateHitCount, id)
	return err
}
