name: Publish to staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read
  packages: write

jobs:
  publish-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get timestamp
        id: time
        run: echo "ts=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: api-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/api
          tags: |
            type=sha,format=short,prefix=staging-${{ steps.time.outputs.ts }}-
      
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.api-meta.outputs.tags }}
          labels: ${{ steps.api-meta.outputs.labels }}

  publish-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get timestamp
        id: time
        run: echo "ts=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: migration-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/migration
          tags: |
            type=sha,format=short,prefix=staging-${{ steps.time.outputs.ts }}-
      
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.migration
          push: true
          tags: ${{ steps.migration-meta.outputs.tags }}
          labels: ${{ steps.migration-meta.outputs.labels }}
