apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: url-minifier
spec:
  template:
    spec:
      initContainers:
        - name: db-migration
          image: ghcr.io/olyxz16/url-minifier/migration:staging-1776208544-68e2a0c # {"$imagepolicy": "flux-system:url-minifier-migration-image-policy"}
      containers:
        - name: api
          image: ghcr.io/olyxz16/url-minifier/api:staging-1776208540-68e2a0c # {"$imagepolicy": "flux-system:url-minifier-api-image-policy"}
