apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: url-minifier
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/olyxz16/url-minifier/api:staging-1776201100-e0cae38 # {"$imagepolicy": "flux-system:url-minifier-image-policy"}
